import Head from 'next/head';
import Image from 'next/image';
import axios from 'axios';
import { useState } from 'react';
import {BsSearch} from 'react-icons/bs';
import Weather from '../components/Weather';
import Spinner from '../components/Spinner';

export default function Home() {

  const[city, setCity] = useState('');
  const[weather, setWeather] = useState({});
  const[loading, setLoading] = useState(false);

  // const url = `https://api.openweathermap.org/data/2.5/weather?q={city name}&appid={API key}`;
  // const url = `https://api.openweathermap.org/data/2.5/weather?q=sarajevo&units=metric&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`;
  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=metric&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`;

  const fetchWeather = (e) => {
    e.preventDefault()
    setLoading(true);
    axios.get(url).then((response) => {
      setWeather(response.data);
      console.log(response.data);
    })
    setCity('');
    setLoading(false);
  }

  if(loading) {
    return <Spinner />
  } else {
    return (
      <div>
        <Head>
          <title>Weather Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
      {/* Overlay div */}
        <div className='absolute top-0 left-0 right-0 bottom-0 bg-black/20 z-[1]'></div>
  
      {/* Background image */}
        <Image src='https://images.unsplash.com/photo-1579619572008-3fe9f19748ea?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80'
               layout='fill'
               className='object-cover'
               alt='Background image'
        />
  
        {/* Search */}
        <div className='relative flex justify-between items-center max-w-[450px] md:max-w-[600px] w-full m-auto pt-4 text-[#f8f8f8] z-10 p-2'>
          <form onSubmit={fetchWeather}
                className='flex justify-between items-center w-full m-auto p-3 bg-transparent border border-gray-300 text-[#f8f8f8] rounded-2xl'>
            <div>
              <input onChange={(e) => setCity(e.target.value)}
                     className='bg-transparent border-none text-[#f8f8f8] focus:outline-none text-2xl placeholder:text-[#b4b4b4]'
                     type="text" 
                     placeholder='Search city' 
              />
            </div>
            <button onClick={fetchWeather}>
              <BsSearch className='mr-2'
                        size={20}/>
            </button>
          </form>
        </div>
  
        {/* Weather data */}
        {weather.main && <Weather data={weather}/>}
      
      </div>
    );
  }
};







// 1. dodajemo const url
// 2. dodajemo useState hooks
// 3. fetchWeather funkciju
// 4. dodajemo dugme Fetch data (kasnije ga izbrisemo)
// 5. dodajemo NextJS Image komponentu
// 6. dodajemo Search div i elemente unutar njega
// 7. input elementu dodajemo onChange dogaadaj
// 8. form elementu dodajemo onSubmit dogadaj
// 9. dodajemo if(loading) uslov za Spinner.jsx komponentu
// 10. 
